name: unminify_mod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, test]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Unminify the mod
      run: sed 's+\\n+\n+g' Skynet\ mod.json > Skynet\ mod\ unminified.txt
    - name: Configure git
      run: |
        git config --local user.name "Github Actions"
        git config --local user.email "actions@github.com"
   # - name: Ensure changes are detected
   #   run: git update-index --refresh -q --unmerged
    - name: If there are changes, amend them to last commit and push
      run: |
         changesMade=false
         git add --all
         git diff-index --quiet HEAD -- || changesMade=true
         $changesMade && echo "Commiting changes"
         $changesMade && git commit --amend --no-edit
         $changesMade && git push --force
         true
